export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";
export const ORDER_DETAILS_RESET = "ORDER_DETAILS_RESET";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const ORDER_LIST_MY_REQUEST = "ORDER_LIST_MY_REQUEST";
export const ORDER_LIST_MY_SUCCESS = "ORDER_LIST_MY_SUCCESS";
export const ORDER_LIST_MY_FAIL = "ORDER_LIST_MY_FAIL";

export const ORDER_SELLER_REQUEST = "ORDER_SELLER_REQUEST";
export const ORDER_SELLER_SUCCESS = "ORDER_SELLER_SUCCESS";
export const ORDER_SELLER_FAIL = "ORDER_SELLER_FAIL";
export const ORDER_SELLER_RESET = "ORDER_SELLER_RESET";

export const PRODUCT_ORDER_SELLER_REQUEST = "PRODUCT_ORDER_SELLER_REQUEST";
export const PRODUCT_ORDER_SELLER_SUCCESS = "PRODUCT_ORDER_SELLER_SUCCESS";
export const PRODUCT_ORDER_SELLER_FAIL = "PRODUCT_ORDER_SELLER_FAIL";
export const PRODUCT_ORDER_SELLER_RESET = "PRODUCT_ORDER_SELLER_RESET";
