export const categories = [
  { title: "Điện tử, công nghệ", img: "/dien-tu.jpg" },
  { title: "Đồ ăn, thực phẩm", img: "/do-an.jpg" },
  { title: "Xe cộ", img: "/xe-co.jpg" },
  { title: "Dịch vụ, du lịch", img: "/dich-vu.jpg" },
  { title: "Gia dụng, nội thất", img: "/noi-that.jpg" },
  { title: "Bất động sản", img: "/bat-dong-san.jpg" },
  { title: "Thời trang, làm đẹp", img: "/thoi-trang.jpg" },
  { title: "Thú cưng", img: "/thu-cung.jpg" },
  { title: "Cây cảnh", img: "/cay-canh.jpeg" },
  { title: "Mẹ và bé", img: "/me-va-be.jpeg" },
  { title: "Thể thao", img: "/the-thao.png" },
  { title: "Đồ dùng văn phòng", img: "/do-van-phong.jpg" },
  { title: "Công, nông nghiệp", img: "/cong-nong-nghiep.jpg" },
];
