export const categories = [
  {
    title: "Thời trang nam",
    img: "/thoi-trang-nam.jpg",
    subCategory: [
      "Áo thun",
      "Áo sơ mi",
      "Áo nỉ/len",
      "Áo khoác",
      "Bộ vest",
      "Bộ đồ thể thao",
      "Quần dài",
      "Quần đùi",
    ],
  },
  {
    title: "Thời trang nữ",
    img: "/thoi-trang-nu.jpg",
    subCategory: [
      "Áo thun",
      "Áo sơ mi",
      "Đồ lót",
      "Áo nỉ/len",
      "Áo khoác",
      "Bộ vest",
      "Đầm",
      "Chân váy",
      "Quần",
    ],
  },
  {
    title: "Giày dép",
    img: "/giay-dep.jpg",
    subCategory: ["Giày da", "Giày thể thao", "Giày sneaker", "Sandals", "Dép"],
  },
  {
    title: "Thủ công mỹ nghệ",
    img: "/thu-cong-my-nghe.jpg",
    subCategory: ["Guột", "Tre", "Mây", "Gỗ", "Cói", "Bèo", "Gốm", "Sứ"],
  },
  {
    title: "Nông sản khô",
    img: "/nong-san-kho.jpg",
    subCategory: ["Bánh đa", "Bún miến", "Măng"],
  },
  // { title: "Xe cộ", img: "/xe-co.jpg" },
  // { title: "Dịch vụ, du lịch", img: "/dich-vu.jpg" },
  // { title: "Gia dụng, nội thất", img: "/noi-that.jpg" },
  // { title: "Bất động sản", img: "/bat-dong-san.jpg" },
  // { title: "Thời trang, làm đẹp", img: "/thoi-trang.jpg" },
  // { title: "Thú cưng", img: "/thu-cung.jpg" },
  // { title: "Cây cảnh", img: "/cay-canh.jpeg" },
  // { title: "Mẹ và bé", img: "/me-va-be.jpeg" },
  // { title: "Thể thao", img: "/the-thao.png" },
  // { title: "Đồ dùng văn phòng", img: "/do-van-phong.jpg" },
  // { title: "Công, nông nghiệp", img: "/cong-nong-nghiep.jpg" },
];
